### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#10]
Периодически вылетает вот такая ошибка:
laravel.ERROR: Undefined property: stdClass::$Train {"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$Train at /public_html/vendor/visavi/rzd-api/src/Rzd/Api.php:120)
[stacktrace]

**Comment by visavi** [comment]
Посмотрю позже, может что-то там поменяли в api

**Comment by alexeydg** [comment]
День добрый. в Api.php в методе trainRoutes есть один недочет.
`$routes = json_decode($this->query->get($this->path, $layer + $params));

        return json_encode($routes->tp[0]->list);`
дело в том, что бывают моменты, когда ржд не отдает $routes->tp и скрипт падает с фатальной ошибкой, тут нужно какую то обработку поставить такой ситуации.

**Comment by visavi** [comment]
Напишите пожалуйста передаваемые параметры, может он что-то другое отдает, надо проверить это
ошибку исправлю

**Comment by alexeydg** [comment]
эта ошибка плавающая, всплывает абсолютно на любых параметрах, просто само апи ржд бывает не отдает эти данные и все, т е просто надо уметь эту ситуацию обрабатывать.

**Comment by visavi** [comment]
https://github.com/visavi/rzd-api/commit/73b7c972244d39656228b82312e36c1f9ac3a7ef
