### ISSUE TITLE
Отображение пересадок

### ISSUE THREAD

**Issue by nashaev** [visavi/rzd-api#11]
Добавьте пожалуйста возможность выбрать маршрут с ПЕРЕСАДКАМИ.
Сейчас только прямые от А до Б, 
- от А до В через пункт Б, не достаются поезда.

**Comment by visavi** [comment]
этот функционал работает, нужно добавить параметр md = 1 в запрос
добавил это в описание

**Comment by nashaev** [comment]
**ОГОНЬ =)**
