### ISSUE TITLE
Данные о расстоянии маршрута

### ISSUE THREAD

**Issue by allcho** [visavi/rzd-api#12]
Привет, данные о расстоянии маршрута есть или нет?

**Comment by visavi** [comment]
А на сайте ржд эта информация есть?

**Comment by sam4488831** [comment]
Доброго времени суток. У меня проблема возникла. Пару лет пользовался API РЖД, теперь банить стало. Возможно это как-то связанно с переходом РЖД на новый сайт? Получается один раз получить маршрут, далее банит. Что сделать чтоб работало? Подскажите пожалуйста sam4488831@mail.ru

**Comment by visavi** [comment]
Возможно такой кто-то с таким же IP совершает запросы, и IP попал в блок
Для обхода есть возможность использовать прокси
```
$config = new Rzd\Config();
$config->setProxy([
    'server' => '192.168.0.1',
    'port'   => '8080',
]);

// Изменяем userAgent по желанию
$config->setUserAgent('Mozilla 5');

// Изменяем referer по желанию
$config->setReferer('rzd.ru');

$api = new Rzd\Api($config);
```

**Comment by visavi** [comment]
> Привет, данные о расстоянии маршрута есть или нет?

Данных о расстоянии не нашел, есть только время между станциями, но это есть в API
Если информация появится, открывайте issue, постараюсь реализовать

**Comment by sam4488831** [comment]
Добрый день. Для нового сайта РЖД API не делали? А то я некоторые данные пытался от туда получить, но не разобрался как. Было бы интересно посмотреть, как вы бы реализовали АПИ по новому сайту
--
Отправлено из Mail.ru для Android вторник, 22 марта 2022г., 02:04 +03:00 от Alexander Grigorev  ***@***.*** :

**Comment by visavi** [comment]
> Добрый день. Для нового сайта РЖД API не делали? А то я некоторые данные пытался от туда получить, но не разобрался как. Было бы интересно посмотреть, как вы бы реализовали АПИ по новому сайту -- Отправлено из Mail.ru для Android вторник, 22 марта 2022г., 02:04 +03:00 от Alexander Grigorev ***@***.*** :

Там вроде как плюс минус  те же самые данные, смысла менять на новый сайт наверно пока нет
А вот разбираться какой параметр за что отвечает придется
Я мельком глянул, там какие-то id городов, нужно найти таблицу сопоставлений или самому составить, если основной api сломается, будем думать
