### ISSUE TITLE
403 на все запросы

### ISSUE THREAD

**Issue by polman123** [visavi/rzd-api#13]
видимо что-то изменилось на стороне rzd, на все запросы стал получать HTTP/1.1 403 Forbidden

**Comment by visavi** [comment]
Постараюсь посмотреть что изменилось в ближайшее время

**Comment by visavi** [comment]
> видимо что-то изменилось на стороне rzd, на все запросы стал получать HTTP/1.1 403 Forbidden

Работоспособность восстановил
