### ISSUE TITLE
проблема с обновлением

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#2]
Добрый день, прокси добавился, но обновится до версии с прокси нельзя, видимо цифра в версии не изменилась

**Comment by visavi** [comment]
там с прокси небольшая проблема, основные запросы без прокси работают, я сегодня завтра все доделаю и добавлю новый тег

**Comment by visavi** [comment]
добавил новую версию
данные возвращаются в json
думаю может сделать чтобы возвращался объект класса, у которого будет 2-3 метода toJson и toArray ну и может toXml
можно будет самому решать в каком формате ему удобнее, ну это как-нибудь потом

если будет нужно что, пишите
