### ISSUE TITLE
проверка данных

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#5]
не всегда от ржд прилетают все данные, в методах нужны проверки, например
```
public function trainCarriages(array $params): string
    {
        $layer = [
            'layer_id' => 5764,
        ];
 
        $routes = json_decode($this->query->get($this->path, $layer + $params));
 
        return json_encode([
            'cars'      => $routes->lst[0]->cars,
            'schemes'   => $routes->schemes,
            'companies' => $routes->insuranceCompany,'functionBlocks' => $routes->lst[0]->functionBlocks,
        ]);
    }
```

   'cars'      => $routes->lst[0]->cars, -- переменной cars может не быть, тогда вылетает ошибка Undefined property: stdClass::$cars

**Comment by visavi** [comment]
А по каким параметрам не возвращается cars 
какие параметры передаете?

**Comment by alexeydg** [comment]
пришлось много с их апи работать с помощью вашего чудесного пакета, сейчас точно не могу дать такой запрос, но факт есть, что по некоторым поездам у них есть такие баги, что прилетают не все данные, нужна проверка. со схемами вагонов у них там тоже колдовство, где то они есть, где то нет. печаль.

**Comment by visavi** [comment]
Добавил проверку
