### ISSUE TITLE
ошибка в описании?

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#6]
из описания:

> необязательные параметр при повтрном запросе
> 
> dir - 0 только в один конец, 1 - туда-обратно
> code0 - код станции отправления
> code1 - код станции прибытия
> dt0 - дата отправления (28.03.2016)
> time0 - время отправления (15:30)
> tnum0 - номер вагона (072Е)
tnum0 - это номер поезда

**Comment by alexeydg** [comment]
там далее еще есть такие ошибки

**Comment by visavi** [comment]
поправил что увидел
