### ISSUE TITLE
языковая версия

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#7]
День добрый
у вас в класcе есть строка  protected $path = 'https://m.rzd.ru/timetable/public/ru';
что позволяет делать запрос только к русской версии, но нужно иметь возможность обращаться и к английской версии  protected https://m.rzd.ru/timetable/public/en
п.с. когда примерно ждать доработки?

**Comment by alexeydg** [comment]
я сделал форк с этими допилами можно их объединить

**Comment by visavi** [comment]
язык добавлен
