### ISSUE TITLE
Закрытая часть

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#8]
Закрытая часть
Информация о пассажирах - Проверка заказа - Оплата заказа - Подтверждение заказа
т е через апи никак не сделать заказ на ржд?

**Comment by visavi** [comment]
Все кроме оплаты сделать не сложно, а с оплатой там есть сложности, например как возвращаться на сайт после оплаты, будет перекидывать на rzd

**Comment by alexeydg** [comment]
мне нужно апи с оформление заказа на ржд. как я понял такого не сделать или реально? можете такое апи добавить?

**Comment by visavi** [comment]
Во-первых как тестировать это? 
Платить каждый раз за билет

Во-вторых нужно понять как происходит оплата,
параметры страницы оплаты мы как-то со страницы заберем,  для этого ее нужно парсить
Формировать форму придется самому, подставлять туда токены итд,
При оплате перекинет на страницу банка, который запросит код из смс
после этого вернет назад на сайт rzd, хотя там может быть где-то в скрытых полях есть returnUrl
Но все это уже не область обязанностей API

Открытого API у них нет, чтобы все это провернуть нужно работать методом научного тыка и каждый раз платить за билет ну или не платить, короче смотреть нужно, 

в-третьих придется еще повозится с авторизацией, так как клиент должен со своего аккаунта все действия выполнять
