### ISSUE TITLE
проблема с прокси

### ISSUE THREAD

**Issue by alexeydg** [visavi/rzd-api#9]
нашел такой баг:
если задать работать через прокси, а прокси например лег, то скрипты никак это не обыгрывают, продолжая работать, как в итоге ошибка скрипта.
Rzd\Query::send в этом методе есть return $this->curl; так вот тут нужно обрабатывать ошибку
if($this->curl->error == true ) .....

**Comment by visavi** [comment]
Спасибо за обратный отзыв, исправлено в https://github.com/visavi/rzd-api/releases/tag/v2.3.0
